app/urls.py
from django.urls import path

from app.views import DashboardView, EncryptionView, DecryptionView


urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("encryption/", EncryptionView.as_view(), name="encryption"),
    path("decryption/", DecryptionView.as_view(), name="decryption"),
    path("decryption/<str:operation>/", DecryptionView.as_view(), name="decryption"),
]

authentication/urls.py
from django.urls import path

from authentication.views import LoginView, RegisterView, ResetPasswordView, LogoutView


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset_password"),
    path("logout/", LogoutView.as_view(), name="logout")
]

config/urls.py
from django.urls import path, include

from config.errors import ErrorPageView


handler400 = "config.errors.bad_request"
handler403 = "config.errors.forbidden"
handler404 = "config.errors.not_found"
handler500 = "config.errors.internal_server_error"

urlpatterns = [
    path("errors/", ErrorPageView.as_view(), name="errors"),
    path("errors/<int:code>/", ErrorPageView.as_view(), name="errors"),

    path("", include(("app.urls", "app"), namespace="app")),

    path(
        "authentication/",
        include(
            ("authentication.urls", "authentication"),
            namespace="authentication"
        )
    ),

    path("download/", include(("download.urls", "download"), namespace="download")),
    path("rbac/", include(("rbac.urls", "rbac"), namespace="rbac"))
]

rbac/urls.py
from django.urls import path, include

from rbac.views import RBACView


urlpatterns = [
    path("", RBACView.as_view(), name="rbac")
]

templates/components/message.html
{% if messages %}
  {% for message in messages %}
    <div class="absolute top-[90%] left-[42%] min-w-80 bg-gray-200 rounded-md" x-data="{ timeout: setTimeout(() => $el.remove(), 5000) }">
      <div class="bg-white border border-gray-300 shadow-md rounded-md p-4 max-w-md">
        <div class="flex items-center justify-center">
          {% if 'error' in message.tags %}
            <svg class="h-4 w-4 text-red-500 mr-2" fill="red" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 490 490" xml:space="preserve">
              <polygon points="456.851,0 245,212.564 33.149,0 0.708,32.337 212.669,245.004 0.708,457.678 33.149,490 245,277.443 456.851,490 489.292,457.678 277.331,245.004 489.292,32.337"/>
            </svg>
          {% else %}
            <svg class="h-6 w-6 text-green-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
          {% endif %}
          <p class="text-gray-800 text-center">{{ message }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/components/modal.html
<div id="modal" class="fixed inset-0 bg-gray-800 bg-opacity-75 hidden flex items-center justify-center z-50">
  <div class="bg-white p-6 rounded shadow-md w-full max-w-md">
    <div class="flex justify-between items-center mb-4">
      <h2 id="modal-title" class="text-2xl font-semibold">Modal Title</h2>
      <button onclick="document.getElementById('modal').classList.add('hidden')" class="text-gray-500 hover:text-gray-600 focus:outline-none">
        <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
          <path fill-rule="evenodd" d="M10 11.414l4.293 4.293a1 1 0 01-1.414 1.414L10 12.828l-3.879 3.879a1 1 0 01-1.414-1.414L8.586 11 4.293 6.707a1 1 0 111.414-1.414L10 9.586l3.879-3.879a1 1 0 011.414 1.414L11.414 11z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <p id="modal-body" class="text-gray-700 mb-4">Modal Body</p>
    <div id="container-actions" class="justify-between">
      <div id="confirmation" class="text-left hidden">
        <button id="confirm-button" onclick="confirmHandler" class="bg-amber-500 text-white px-4 py-2 rounded-md hover:bg-amber-600 focus:outline-none focus:bg-amber-600">Konfirmasi</button>
      </div>
      <div class="text-right">
        <button onclick="document.getElementById('modal').classList.add('hidden')" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600">Tutup</button>
      </div>
    </div>
  </div>
</div>

<script>
  const showModal = (title, body, modalType, onConfirmed) => {
    document.getElementById('modal').classList.remove('hidden');
    document.getElementById('modal-title').textContent = title;
    document.getElementById('modal-body').textContent = body;

    if (modalType === "confirmation") {
      document.getElementById('container-actions').classList.add('flex');
      document.getElementById('confirmation').classList.remove('hidden');

      const confirmHandler = () => {
        onConfirmed();
      };

      document.getElementById('confirm-button').addEventListener('click', confirmHandler);
    }
  }
</script>

templates/components/modal_form.html
<div id="modal-form" class="fixed inset-0 bg-gray-800 bg-opacity-75 hidden flex items-center justify-center z-50">
  <div class="bg-white p-6 rounded shadow-md w-full max-w-md">
    <div class="flex justify-between items-center mb-4">
      <h2 id="modal-form-title" class="text-2xl font-semibold">Modal Title</h2>
      <button onclick="document.getElementById('modal-form').classList.add('hidden')" class="text-gray-500 hover:text-gray-600 focus:outline-none">
        <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
          <path fill-rule="evenodd" d="M10 11.414l4.293 4.293a1 1 0 01-1.414 1.414L10 12.828l-3.879 3.879a1 1 0 01-1.414-1.414L8.586 11 4.293 6.707a1 1 0 111.414-1.414L10 9.586l3.879-3.879a1 1 0 011.414 1.414L11.414 11z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <form id="modal-form" method="post">
      <div id="form-body" class="text-gray-700 mb-4">
        {% csrf_token %}
      </div>
      <div class="flex justify-between">
        <div id="submit" class="text-left">
          <button type="submit" class="bg-amber-500 text-white px-4 py-2 rounded-md hover:bg-amber-600 focus:outline-none focus:bg-amber-600">Konfirmasi</button>
        </div>
        <div class="text-right">
          <button type="button" onclick="document.getElementById('modal-form').classList.add('hidden')" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600">Tutup</button>
        </div>
      </div>
    </form>
  </div>
</div>

<script>
  const showModalForm = (title, forms, onSubmit) => {
    document.getElementById('modal-form').classList.remove('hidden');
    document.getElementById('modal-form-title').textContent = title;
    const formBody = document.getElementById('form-body');

    while (formBody.childElementCount > 1) {
      formBody.removeChild(formBody.lastChild);
    }

    forms.forEach(form => {
      const inputElement = document.createElement('input');
      inputElement.type = form.type ?? 'text';
      inputElement.name = form.name ?? '';
      inputElement.value = form.value ?? '';
      inputElement.required = form.required ?? false;
      inputElement.minLength = 8;
      inputElement.maxLength = 16;
      inputElement.placeholder = form.placeholder ?? '';
      inputElement.classList.add('w-full', 'px-4', 'py-2', 'border', 'border-gray-300', 'rounded-md', 'focus:outline-none', 'focus:border-sky-500', 'focus:ring-1', 'focus:ring-sky-500');

      if (form.type !== 'hidden') {
        const labelElement = document.createElement('label');
        labelElement.textContent = form.label;
        labelElement.htmlFor = form.name;
        labelElement.classList.add('block', 'text-gray-700', 'font-medium', 'mb-2');
        formBody.appendChild(labelElement);
      }
      formBody.appendChild(inputElement);
    });

    document.getElementById('modal-form').addEventListener('submit', (event) => {
      event.preventDefault();
      const formData = {};

      forms.forEach(form => {
        const inputElement = formBody.querySelector(`[name="${form.name}"]`);
        if (inputElement) {
          formData[form.name] = inputElement.value;
        }
      });
  
      onSubmit(formData);
    });
  }
</script>

templates/components/sidebar.html
{% load static %}

<div class="bg-gray-800 text-white w-64 flex flex-col">

  <div class="p-4 border-b border-gray-700">
    <img src="{% static 'favicon.ico' %}" alt="App Logo" class="w-20 m-auto"/>
    <div class="my-3"></div>
    <h1 class="text-xl text-center font-semibold">AES Blowfish App</h1>
  </div>

  <nav class="flex-1 overflow-y-auto">
    <a href="{% url 'app:dashboard' %}" class="{% if current_url == 'dashboard' %} text-white {% else %} text-gray-400 {% endif %} block py-2 px-4 hover:text-white">
      <div class="min-w-20 flex justify-between items-center">
        <p class="mx-2">Dashboard</p>
        <i class="bx bxs-dashboard text-lg"></i>
      </div>
    </a>
    <a href="{% url 'app:encryption' %}" class="{% if current_url == 'encryption' %} text-white {% else %} text-gray-400 {% endif %} block py-2 px-4 hover:text-white">
      <div class="min-w-20 flex justify-between items-center">
        <p class="mx-2">Enkripsi</p>
        <i class="bx bxs-lock text-lg"></i>
      </div>
    </a>
    <a href="{% url 'app:decryption' %}" class="{% if current_url == 'decryption' %} text-white {% else %} text-gray-400 {% endif %} block py-2 px-4 hover:text-white">
      <div class="min-w-20 flex justify-between items-center">
        <p class="mx-2">Dekripsi</p>
        <i class="bx bx-lock-open-alt text-lg"></i>
      </div>
    </a>
    <a href="{% url 'rbac:rbac' %}" class="{% if current_url == 'rbac' %} text-white {% else %} text-gray-400 {% endif %} block py-2 px-4 hover:text-white">
      <div class="min-w-20 flex justify-between items-center">
        <p class="mx-2">Manajemen Hak Akses</p>
        <i class="bx bxs-cog text-lg"></i>
      </div>
    </a>
    <a href="{% url 'authentication:logout' %}" class="block py-2 px-4 text-gray-400 hover:text-white">
      <div class="min-w-20 flex justify-between items-center">
        <p class="mx-2">Logout</p>
        <i class="bx bxs-log-out-circle text-lg"></i>
      </div>
    </a>
  </nav>

  <div class="flex-1"></div>

  <div class="block py-2 px-4 text-gray-400 bg-gray-900">
    <div class="min-w-32 flex items-center">
      {% if request.session.role|lower == 'admin' %}
        <i class='bx bx-crown text-4xl'></i>
      {% else %}
        <i class="bx bx-user-circle text-4xl"></i>
      {% endif %}
      <div class="mx-2"></div>
      <div class="w-full">
        <p class="mx-2 font-bold">{{ request.session.user|title }}</p>
        <p class="mx-2">{{ request.session.role|title }}</p>
      </div>
    </div>
  </div>

</div>