app/urls.py
from django.urls import path

from app.views import DashboardView, EncryptionView, DecryptionView


urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("encryption/", EncryptionView.as_view(), name="encryption"),
    path("decryption/", DecryptionView.as_view(), name="decryption"),
    path("decryption/<str:operation>/", DecryptionView.as_view(), name="decryption"),
]

config/urls.py
from django.urls import path, include

from config.errors import ErrorPageView


handler400 = "config.errors.bad_request"
handler403 = "config.errors.forbidden"
handler404 = "config.errors.not_found"
handler500 = "config.errors.internal_server_error"

urlpatterns = [
    path("errors/", ErrorPageView.as_view(), name="errors"),
    path("errors/<int:code>/", ErrorPageView.as_view(), name="errors"),

    path("", include(("app.urls", "app"), namespace="app")),

    path(
        "authentication/",
        include(
            ("authentication.urls", "authentication"),
            namespace="authentication"
        )
    ),

    path("download/", include(("download.urls", "download"), namespace="download")),
    path("rbac/", include(("rbac.urls", "rbac"), namespace="rbac"))
]

download/urls.py
from django.urls import path

from download.views import ObjectDownloadView


urlpatterns = [
    path("<str:oid>/", ObjectDownloadView.as_view(), name="object"),
]

app/templates/dashboard.html
{% extends "bases/app.html" %}

{% block title %}Dashboard{% endblock title %}

{% block body %}
  <div class="bg-gray-800 p-4 flex justify-center items-center text-white font-bold mb-10">
    Dashboard
  </div>

  <div class="flex justify-evenly mt-2 w-full">
    <div class="w-[50%] grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
      <div class="p-2 rounded shadow">
        <div class="flex items-center justify-evenly">
          <i class="bx bxs-data text-pink-800 text-4xl opacity-60"></i>
          <div class="ml-2">
            <h2 class="text-gray-700 text-lg font-semibold mb-2">File di Server</h2>
            <p class="text-gray-500 text-2xl font-bold">{{ server_files_count }}</p>
          </div>
        </div>
      </div>
      <div class="p-2 rounded shadow">
        <div class="flex items-center justify-evenly">
          <i class="bx bx-lock text-orange-800 text-4xl opacity-60"></i>
          <div class="ml-2">
            <h2 class="text-gray-700 text-lg font-semibold mb-2">File Terenkripsi</h2>
            <p class="text-gray-500 text-2xl font-bold">{{ encrypted_count }}</p>
          </div>
        </div>
      </div>
      <div class="p-2 rounded shadow">
        <div class="flex items-center justify-evenly">
          <i class="bx bx-lock-open text-orange-800 text-4xl opacity-60"></i>
          <div class="ml-2">
            <h2 class="text-gray-700 text-lg font-semibold mb-2">File Terdekripsi</h2>
            <p class="text-gray-500 text-2xl font-bold">{{ decrypted_count }}</p>
          </div>
        </div>
      </div>
      <div class="p-2 rounded shadow">
        <div class="flex items-center justify-evenly">
          <i class="bx bxs-folder-open text-yellow-800 text-4xl opacity-60"></i>
          <div class="ml-2">
            <h2 class="text-gray-700 text-lg font-semibold mb-2">File Total</h2>
            <p class="text-gray-500 text-2xl font-bold">{{ total_files_count }}</p>
          </div>
        </div>
      </div>
      <div class="p-2 rounded shadow">
        <div class="flex items-center justify-evenly">
          <i class="bx bxs-user text-green-800 text-4xl opacity-60"></i>
          <div class="ml-2">
            <h2 class="text-gray-700 text-lg font-semibold mb-2">Akun Pengguna</h2>
            <p class="text-gray-500 text-2xl font-bold">{{ users_count }}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="w-60 min-h-60 p-2 rounded shadow">
      <h2 class="text-gray-700 text-lg text-center font-semibold mb-2">Aktivitas Terbaru</h2>
      <div class="p-4 bg-gray-100 rounded flex flex-col">
        {% if recent_activities|length == 0 %}
          <i class="bx bx-ghost text-center text-4xl text-gray-500"></i>
          <div class="my-2"></div>
          <p class="text-gray-500 text-sm text-center">Belum ada aktivitas</p>
        {% endif %}

        {% for activity in recent_activities %}
          <div class="flex items-center mb-2">
            <i class="{{ activity.box_icon }} {{ activity.tw_color }} text-xl mr-2"></i>
            <div>
              <p class="text-gray-700 text-sm">{{ activity.action }}</p>
              <p class="text-gray-500 text-xs">{{ activity.user }}</p>
              <div class="flex justify-between items-center">
                <p class="text-gray-500 text-xs">{{ activity.time_difference }}</p>
                <i class="bx bxs-watch text-gray-500 text-sm mx-1"></i>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock body %}

app/templates/decryption.html
{% extends "bases/app.html" %}

{% block title %}Dekripsi{% endblock title %}

{% block body %}
  <div class="bg-gray-800 p-4 flex justify-center items-center text-white font-bold mb-10">
    Decryption
  </div>

  {% include "components/modal_form.html" %}

  <div class="container mx-auto p-8 bg-white rounded shadow-md">
    <div class="bg-white p-8 rounded flex justify-between">
      <h2 class="text-2xl font-semibold mb-4">Server Data</h2>
      <div class="flex" x-data="{ keyword: '{{ active_search }}' }">
        <input type="text" x-model="keyword" placeholder="Pencarian berdasarkan Kode" class="flex-grow py-2 px-4 border border-gray-300 rounded-l-md focus:outline-none focus:border-sky-500" />
        <a x-bind:href="'?search=' + keyword" class="bg-sky-600 text-white py-4 px-4 rounded-r-md hover:bg-sky-600 focus:outline-none focus:bg-sky-600 cursor-pointer">Cari</a>
      </div>
    </div>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-white">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm leading-4 text-gray-600 uppercase tracking-wider">No.</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm leading-4 text-gray-600 uppercase tracking-wider">User</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm leading-4 text-gray-600 uppercase tracking-wider">File</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm leading-4 text-gray-600 uppercase tracking-wider">Kode</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm leading-4 text-gray-600 uppercase tracking-wider">Tanggal</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm leading-4 text-gray-600 uppercase tracking-wider">Status</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm leading-4 text-gray-600 uppercase tracking-wider">Action</th>
          </tr>
        </thead>
        <tbody>
          {% if data|length_is:0 %}
            <tr>
              <td colspan="7">
                <div class="text-center opacity-70">
                  <i class="bx bx-x text-neutral-700 text-9xl"></i>
                  <p>Data Tidak Ada</p>
                </div>
              </td>
            </tr>
          {% endif %}

          {% for row in data %}
            <tr>
              <td class="py-2 px-4 border-b border-gray-200">{{ forloop.counter0|add:meta.current_page }}.</td>
              <td class="py-2 px-4 border-b border-gray-200">{{ row.user.fullname }}</td>
              <td class="py-2 px-4 border-b border-gray-200">{{ row.file.filename }}</td>
              <td class="py-2 px-4 border-b border-gray-200">{{ row.name }}</td>
              <td class="py-2 px-4 border-b border-gray-200">{{ row.file.date_created }}</td>
              <td class="py-2 px-4 border-b border-gray-200">
                {% if row.status|lower == 'encrypted' %}
                  <div class="p-2 bg-sky-600 text-white rounded text-center text-sm font-bold">
                    {{ row.status }}
                  </div>
                {% endif %}
                {% if row.status|lower == 'decrypted' %}
                  <div class="p-2 bg-amber-500 text-white rounded text-center text-sm font-bold">
                    {{ row.status }}
                  </div>
                {% endif %}
              </td>
              <td class="py-2 px-4 border-b border-gray-200">
                <div class="flex justify-evenly">
                  <a href="{% url 'download:object' row.file.oid %}"><i class="text-teal-600 bx bx-download text-2xl"></i></a>
                  {% if row.status|lower == 'encrypted' %}
                    <form class="decryption-form" data-action="decrypt" action="{% url 'app:decryption' 'decrypt' %}" method="post">
                      <input type="hidden" name="oid" value="{{ row.oid }}">
                      <button type="submit"><i class="text-amber-500 bx bxs-lock-open text-2xl"></i></button>
                      {% csrf_token %}
                    </form>
                    <form class="decryption-form" data-action="delete" action="{% url 'app:decryption' 'delete' %}" method="post">
                      <input type="hidden" name="oid" value="{{ row.oid }}">
                      <button type="submit"><i class="text-red-700 bx bxs-trash text-2xl"></i></button>
                      {% csrf_token %}
                    </form>
                  {% endif %}
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock body %}

{% block script %}
  <script>
    document.querySelectorAll('.decryption-form').forEach(form => {
      form.addEventListener('submit', function(event) {
        event.preventDefault();
        const oid = form.querySelector('input').value;
        const action = form.getAttribute('data-action');

        if (action == 'decrypt') {
          showModalForm(
            "Dekripsi File",
            [
              { type: "hidden", name: "oid", label: "OID", value: oid },
              { type: "text", name: "key", label: "Kunci", placeholder: "Masukkan Kunci Enkripsi", required: true }
            ],
            (data) => {
              for (const key in data) {
                const addedInput = document.createElement('input');

                addedInput.name = key;
                addedInput.type = 'hidden';
                addedInput.value = data[key];
                form.appendChild(addedInput);
              }

              form.submit();
            }
          )
        } else {
          showModal("Hapus File", "Jika transaksi ini dihapus, maka file tidak dapat dikembalikan atau didekripsi. Yakin ingin menghapus?", "confirmation", () => {
            form.submit();
          })
        }
      })
    })
  </script>
{% endblock script %}

app/templates/encryption.html
{% extends "bases/app.html" %}

{% block title %}Enkripsi{% endblock title %}

{% block body %}
  <div class="bg-gray-800 p-4 flex justify-center items-center text-white font-bold mb-10">
    Encryption
  </div>

  <div id="validation" class="flex justify-center items-center" x-data="{ valid: false }">
    <div class="bg-white p-8 rounded shadow-md w-full max-w-md">
      <h2 class="text-2xl font-semibold mb-4">Enkripsi File</h2>
      <form method="post" action="{% url 'app:encryption' %}" enctype="multipart/form-data">
        <div class="mb-4">
          <label for="file" class="block text-gray-700 font-medium mb-2">Pilih dan upload file untuk dienkripsi:</label>
          <input type="file" id="file" name="file" class="w-full border rounded-md px-4 py-2 focus:outline-none focus:border-blue-500"/>
        </div>
        <div class="mb-4">
          <label for="key" class="block text-gray-700 font-medium mb-2">Kunci Enkripsi:</label>
          <input type="text" id="key" name="key" class="w-full border rounded-md px-4 py-2 focus:outline-none focus:border-blue-500" placeholder="Masukan kunci enkripsi anda (min 8 karakter)" minlength="8" maxlength="56"/>
        </div>
        <button x-bind:type="valid ? 'submit' : 'button'" id="encryptionForm" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600">Encrypt</button>
        {% csrf_token %}
      </form>
    </div>
  </div>

  {% if success %}
    <div class="flex justify-center items-center mt-10">
      <div class="bg-white p-8 min-w-80 text-center rounded shadow-md">
        <p>
          File Berhasil Dienkripsi! <br/>
          <strong>Waktu Pemrosesan :</strong> {{ elapsed_time }} detik <br/>
          <strong>Blowfish Validation Key :</strong> {{ validation_key }}<br/>
          <strong>Kode :</strong> {{ name }} <br/>
          <strong>Ukuran :</strong> {{ size }} <br/>
          <strong>Checksum :</strong> {{ checksum }}
        </p>
        <button onclick="window.location.href='{% url 'download:object' oid %}'" class="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-700 focus:outline-none focus:bg-green-700">
          <i class='bx bxs-file-{{ extension }}'></i>
          Unduh
        </button>
      </div>
    </div>
  {% endif %}
{% endblock body %}

{% block script %}
  <script>
    document.getElementById('encryptionForm').addEventListener('click', function(event) {
      const fileInput = document.getElementById('file').files[0];
      const encryptionKey = document.getElementById('key').value;
      const formValidation = document.getElementById('validation');

      if (!fileInput || !encryptionKey) {
        showModal("Error", "Harap pilih file dan masukkan kunci enkripsi.");
        return;
      }

      const componentData = Alpine.$data(formValidation);
      componentData.valid = true;
    });
  </script>
{% endblock script %}